In [3]:
import pandas as pd

<h1>Exploração de dados inicial.</h1>
<h2>Nessa etapa, busca-se realizar uma exploração de dados</h2>

carregando os datasets ao notebooks

In [4]:
df_titles = pd.read_csv(r'..\datasets\title.akas.tsv', sep='\t')
df_titles_basic = pd.read_csv(r'..\datasets\title.basics.tsv', sep='\t')
df_titles_episode = pd.read_csv(r'..\datasets\title.episode.tsv', sep='\t')
df_titles_principals = pd.read_csv(r'..\datasets\title.principals.tsv', sep='\t')
df_titles_ratings = pd.read_csv(r'..\datasets\title.ratings.tsv', sep='\t')

informações dos respectivos dataframes

In [6]:

df_titles.info();
df_titles.head()

<class 'pandas.DataFrame'>
RangeIndex: 55754007 entries, 0 to 55754006
Data columns (total 8 columns):
 #   Column           Dtype
---  ------           -----
 0   titleId          str
 1   ordering         int64
 2   title            str
 3   region           str
 4   language         str
 5   types            str
 6   attributes       str
 7   isOriginalTitle  int64
dtypes: int64(2), str(6)
memory usage: 3.3 GB

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
0,tt0000001,1,Carmencita,\N,\N,original,\N,1
1,tt0000001,2,Carmencita,DE,\N,\N,literal title,0
2,tt0000001,3,Carmencita,US,\N,imdbDisplay,\N,0
3,tt0000001,4,Carmencita - spanyol tánc,HU,\N,imdbDisplay,\N,0
4,tt0000001,5,Καρμενσίτα,GR,\N,imdbDisplay,\N,0

In [5]:
#verificando regiões mais comuns
lista_regioes = list(df_titles.region.value_counts().index)
print(lista_regioes)

['\\N', 'DE', 'JP', 'FR', 'IN', 'ES', 'IT', 'PT', 'US', 'GB', 'CA', 'AU', 'XWW', 'BR', 'RU', 'MX', 'PL', 'GR', 'FI', 'SE', 'ZA', 'HU', 'IE', 'NZ', 'AR', 'PH', 'NL', 'NO', 'DK', 'TR', 'CN', 'XWG', 'TW', 'SUHH', 'BE', 'EC', 'HK', 'KR', 'RO', 'UA', 'SG', 'AT', 'EE', 'BG', 'CZ', 'RS', 'IR', 'IL', 'XYU', 'HR', 'CH', 'AE', 'VN', 'CL', 'ID', 'VE', 'EG', 'LT', 'SK', 'TH', 'NG', 'CO', 'CSHH', 'SI', 'DDDE', 'PE', 'UY', 'XEU', 'LV', 'PK', 'MY', 'BD', 'KZ', 'DO', 'IS', 'UZ', 'XAS', 'CU', 'BA', 'AZ', 'AL', 'LB', 'PR', 'LK', 'TN', 'GE', 'NP', 'MA', 'MK', 'BY', 'SA', 'CY', 'LU', 'KE', 'CM', 'GH', 'DZ', 'UG', 'CR', 'PA', 'SY', 'AM', 'YUCS', 'JM', 'BO', 'KP', 'HT', 'IQ', 'KW', 'QA', 'LI', 'MT', 'KH', 'BF', 'SN', 'PY', 'XKO', 'MN', 'JO', 'GT', 'TZ', 'ME', 'XKV', 'MD', 'TT', 'CI', 'KG', 'PS', 'ZW', 'MM', 'SV', 'AF', 'CG', 'CD', 'XSA', 'BJ', 'GI', 'TG', 'MZ', 'ZM', 'BH', 'SM', 'ET', 'SL', 'HN', 'MC', 'GA', 'RW', 'AO', 'MO', 'BS', 'CSXX', 'MV', 'MG', 'NI', 'MW', 'BW', 'LR', 'TJ', 'MU', 'ML', 'VI', 'GP', 'GL', 'SD', 'PF', 'YE', 'NE', 'FO', 'LA', 'TM', 'GM', 'GN', 'BB', 'BT', 'TD', 'LY', 'AD', 'GU', 'BI', 'BUMM', 'XPI', 'MQ', 'VDVN', 'CV', 'OM', 'GQ', 'CF', 'AW', 'KY', 'IM', 'FJ', 'BM', 'SO', 'SC', 'AN', 'BN', 'SZ', 'SR', 'BZ', 'GF', 'GY', 'PG', 'RE', 'AG', 'NC', 'VU', 'DM', 'LC', 'MR', 'CW', 'GW', 'TO', 'TL', 'WS', 'ER', 'VG', 'AQ', 'LS', 'KM', 'MH', 'VC', 'AS', 'VA', 'ST', 'SB', 'GD', 'TC', 'EH', 'FM', 'XSI', 'ZRCD', 'SH', 'MP', 'AI', 'KI', 'KN', 'XAU', 'NR', 'MS', 'CK', 'DJ', 'PN', 'CC', 'TV', 'NU', 'SJ', 'XNA', 'PW', 'FK', 'JE']

In [7]:
df_titles_brasil = df_titles[df_titles['region'] == 'BR']
df_titles_brasil.info()
df_titles_brasil.shape

<class 'pandas.DataFrame'>
Index: 143178 entries, 108 to 55753688
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   titleId          143178 non-null  str
 1   ordering         143178 non-null  int64
 2   title            143178 non-null  str
 3   region           143178 non-null  str
 4   language         143178 non-null  str
 5   types            143178 non-null  str
 6   attributes       143178 non-null  str
 7   isOriginalTitle  143178 non-null  int64
dtypes: int64(2), str(6)
memory usage: 9.8 MB

(143178, 8)

In [8]:
print('Há {} títulos na região brasileira.'.format(df_titles_brasil.shape[0]))

Há 143178 títulos na região brasileira.

In [36]:
df_titles_basic.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Poor Pierrot,Pauvre Pierrot,0,1892,\N,5,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,Short

In [28]:
df_titles_basic.titleType.value_counts()

titleType
tvEpisode       9591630
short           1123840
movie            742654
video            324200
tvSeries         297520
tvMovie          154499
tvMiniSeries      69384
tvSpecial         57641
videoGame         48630
tvShort           10967
tvPilot               1
Name: count, dtype: int64

In [27]:
print('Para este projeto, será considerado apenas os filmes, ou seja, os títulos do tipo "movie".')

Para este projeto, será considerado apenas os filmes, ou seja, os títulos do tipo "movie".

In [ ]:

df_titles_episode.head()

,tconst,ordering,nconst,category,job,characters
0,tt0000001,1.0,nm1588970,self,\N,"[""Self""]"
1,tt0000001,2.0,nm0005690,director,\N,\N
2,tt0000001,3.0,nm0005690,producer,producer,\N
3,tt0000001,4.0,nm0374658,cinematographer,director of photography,\N
4,tt0000002,1.0,nm0721526,director,\N,\N

In [33]:
df_titles_principals.head()

,tconst,ordering,nconst,category,job,characters
0,tt0000001,1.0,nm1588970,self,\N,"[""Self""]"
1,tt0000001,2.0,nm0005690,director,\N,\N
2,tt0000001,3.0,nm0005690,producer,producer,\N
3,tt0000001,4.0,nm0374658,cinematographer,director of photography,\N
4,tt0000002,1.0,nm0721526,director,\N,\N

In [34]:
df_titles_ratings.head()

      tconst  averageRating  numVotes
0  tt0000001            5.7      2201
1  tt0000002            5.5       312
2  tt0000003            6.4      2314
3  tt0000004            5.1       197
4  tt0000005            6.2      3039

In [59]:
df_title_brasil_basic =  df_titles_brasil.merge(df_titles_basic, how='left', left_on='titleId', right_on='tconst').reset_index()
df_title_brasil_basic.head()

,index,titleId,ordering,title,region,language,types,attributes,isOriginalTitle,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,0,tt0000010,6,A Saída dos Operários da Fábrica Lumière,BR,\N,\N,\N,0,tt0000010,short,Leaving the Factory,La sortie de l'usine Lumière à Lyon,0,1895,\N,1,"Documentary,Short"
1,1,tt0000012,10,A Chegada de um Trem à Estação,BR,\N,imdbDisplay,\N,0,tt0000012,short,The Arrival of a Train,L'arrivée d'un train à La Ciotat,0,1896,\N,1,"Documentary,Short"
2,2,tt0000014,12,O Regador Regado,BR,\N,imdbDisplay,\N,0,tt0000014,short,The Waterer Watered,L'arroseur arrosé,0,1895,\N,1,"Comedy,Short"
3,3,tt0000028,5,A Pesca do Peixe Dourado,BR,\N,imdbDisplay,\N,0,tt0000028,short,Fishing for Goldfish,La pêche aux poissons rouges,0,1895,\N,1,"Documentary,Short"
4,4,tt0000029,21,O Almoço do Bebê,BR,\N,imdbDisplay,\N,0,tt0000029,short,Baby's Meal,Repas de bébé,0,1895,\N,1,"Documentary,Short"

In [78]:
df_brasil_movies = df_title_brasil_basic.merge(df_titles_ratings, how='left', left_on='titleId', right_on='tconst')
df_brasil_movies.head()

,index,titleId,ordering,title,region,language,types,attributes,isOriginalTitle,tconst_x,...,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,tconst_y,averageRating,numVotes
0,0,tt0000010,6,A Saída dos Operários da Fábrica Lumière,BR,\N,\N,\N,0,tt0000010,...,Leaving the Factory,La sortie de l'usine Lumière à Lyon,0,1895,\N,1,"Documentary,Short",tt0000010,6.8,8289.0
1,1,tt0000012,10,A Chegada de um Trem à Estação,BR,\N,imdbDisplay,\N,0,tt0000012,...,The Arrival of a Train,L'arrivée d'un train à La Ciotat,0,1896,\N,1,"Documentary,Short",tt0000012,7.4,13969.0
2,2,tt0000014,12,O Regador Regado,BR,\N,imdbDisplay,\N,0,tt0000014,...,The Waterer Watered,L'arroseur arrosé,0,1895,\N,1,"Comedy,Short",tt0000014,7.1,6406.0
3,3,tt0000028,5,A Pesca do Peixe Dourado,BR,\N,imdbDisplay,\N,0,tt0000028,...,Fishing for Goldfish,La pêche aux poissons rouges,0,1895,\N,1,"Documentary,Short",tt0000028,5.1,1256.0
4,4,tt0000029,21,O Almoço do Bebê,BR,\N,imdbDisplay,\N,0,tt0000029,...,Baby's Meal,Repas de bébé,0,1895,\N,1,"Documentary,Short",tt0000029,5.9,3794.0

In [80]:
df_brasil_movies = df_brasil_movies[df_brasil_movies.titleType == 'movie']
df_brasil_movies.titleType.value_counts()

titleType
movie    78896
Name: count, dtype: int64

In [81]:
#salvando dataset de filmes brasileiros em um arquivo csv
df_brasil_movies.to_csv(r'..\datasets\filmes_brasileiros.csv', index=False)